cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^create/$',
            views.order_create,
            name='order_create'),
]

sportsbangla/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from sportsbangla import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$',views.login_redirect , name='login_redirect'),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^admin/', admin.site.urls),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import  login_required
from django.views.decorators.http import require_POST


from accounts.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
@login_required
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
   <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
        <th scope="col">Total</th>
        <th> </th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
    {% with product=item.product %}
        <tr>
          <td >
              <div class="media">
                <a href="{{ product.get_absolute_url }}">
                    <img class="media-object"
                         src="{% if product.image %}{{ product.image.url }}
                              {% else %}{% static "img/no_image.png" %}{% endif %}"
                         style="width: 72px; height: 72px;">
                </a>
                <div>
                    <h4><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                    <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                </div>
              </div>
          </td>
          <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_field item.update_quantity_form.quantity show_label=False %}
                                    {% bootstrap_field item.update_quantity_form.update %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success btn-product">
                                            Update
                                        </button>
                                    {% endbuttons %}
              </form>
          </td>
          <td><strong>BDT {{ item.price }}</strong></td>
            <td><strong>BDT {{ item.total_price }}</strong></td>
            <td><a href="{% url "cart:cart_remove" product.id %}" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Remove
                                </a></td>
            {% endwith %}
            {% endfor %}
        </tr>

        <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>Total</h3></td>
                    <td><h3><strong>BDT {{ cart.get_total_price }}</strong></h3></td>
        </tr>
        <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>
                        <a href="/account/product_list" class="btn btn-default">
                            Continue Shopping <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url "orders:order_create" %}" class="btn btn-default">Checkout <i
                                class="glyphicon glyphicon-play" aria-hidden="true"></i>
                        </a>
                    </td>
        </tr>
  </tbody>
</table>

{% endblock %}